#include <string.h>

void bzero(void*dest,size_t len)
{
	__asm__ volatile(
	"	move.l	%d2,%sp@-\n"
	"	movl	12(%fp),%d1		| count\n"
	"	movl	8(%fp),%a0		| destination\n"
	"	movql	#0,%d2\n"
	"	cmpl	#8,%d1\n"
	"	jlt	Lbzero_bloop\n"
	"	movl	%a0,%d0\n"
	"	btst	#0,%d0			| if (dst & 1)\n"
	"	jeq	Lbzero_algndw		| \n"
	"	movb	%d2,%a0@+		|*(char *)dst++ = 0\n"
	"	subql	#1,%d1			|len--\n"
	"Lbzero_algndw:\n"
	"	/* long word align */\n"
	"	btst	#1,%d0			| if (dst & 2)\n"
	"	jeq	Lbzero_algndl		|\n"
	"	movw	%d2,%a0@+		|*(short *)dst++ = 0\n"
	"	subql	#2,%d1			|len -= 2\n"
	"Lbzero_algndl:\n"
	"	/* zero by 8 longwords */\n"
	"	movel	%d1,%d0\n"
	"	lsrl	#5,%d0			| cnt = len / 32\n"
	"	jeq	Lbzero_long		| if (cnt)\n"
	"	andl	#31,%d1			|len %= 32\n"
	"Lbzero_32loop:\n"
	"	movl	%d2,%a0@+		|zero 8 long words\n"
	"	movl	%d2,%a0@+\n"
	"	movl	%d2,%a0@+\n"
	"	movl	%d2,%a0@+\n"
	"	movl	%d2,%a0@+\n"
	"	movl	%d2,%a0@+\n"
	"	movl	%d2,%a0@+\n"
	"	movl	%d2,%a0@+\n"
	"	subql	#1,%d0\n"
	"	jne	Lbzero_32loop		|till done\n"
	"Lbzero_long:\n"
	"	movel	%d1,%d0\n"
	"	lsrl	#2,%d0			| cnt = len / 4\n"
	"	jeq	Lbzero_bloop		| if (cnt)\n"
	"Lbzero_lloop:\n"
	"	movl	%d2,%a0@+		|	clear longwords\n"
	"	subql	#1,%d0\n"
	"	jne	Lbzero_lloop		|	till done\n"
	"	andl	#3,%d1			|	len %= 4\n"
	"	jeq	Lbzero_done\n"
	"Lbzero_bloop:\n"
	"	tst.l   %d1\n"
	"	jeq	Lbzero_done\n"
	"	movb	%d2,%a0@+		| zero bytes\n"
	"Lbzero_byte:\n"
	"	subql	#1,%d1\n"
	"	jne	Lbzero_bloop		| till done\n"
	"Lbzero_done:\n"
	"	movl	%sp@+,%d2\n"
	);
}
libc_hidden_def(memmove)
