all:
	/opt/nivis/m68k-unknown-linux-uclibc/bin/m68k-unknown-linux-uclibc-gcc -O0 main.c memmove.c bcopy.c memcpy.c
	#/opt/nivis/m68k-unknown-linux-uclibc/bin/m68k-unknown-linux-uclibc-gcc main.c
	scp a.out nivis@10.32.0.170:~/mariusn/
